FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block shibd_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user("shibboleth") }}

{% set shibd_packages = ["shibboleth-sp2-utils"] %}

{{ macros.install_packages(shibd_packages | customizable("packages")) }}

# fix log paths
RUN sed -i 's#/var/log/shibboleth#/var/log/kolla#' /etc/shibboleth/shibd.logger /etc/shibboleth/native.logger /etc/shibboleth/console.logger /etc/shibboleth/syslog.logger

{% block shibd_footer %}{% endblock %}
{% block footer %}{% endblock %}

ADD start.sh /usr/local/bin/kolla_start
# CMD ["bash", "-c", "shibd -t && shibd -fc /etc/shibboleth/shibboleth2.xml"]
