FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block shibd_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% set shibd_packages = ["shibboleth-sp2-utils"] %}

{{ macros.install_packages(shibd_packages | customizable("packages")) }}

{% block shibd_footer %}{% endblock %}
{% block footer %}{% endblock %}

