FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block shibd_header %}{% endblock %}

{% import "macros.j2" as macros with context %}



{% block shibd_footer %}{% endblock %}
{% block footer %}{% endblock %}

